title: Recipe

icon: 🥪

status:
  draft: true
  listed: true

columns:
  - width: 1/1
    fields:
      headline:
        type: text
  - width: 1/3
    fields:
      cover:
        type: image-clip
        layout: cards
        template: cover
        multiple: false
        clip:
          minwidth: 800
          minheight: 450
          ratio: fixed
  - width: 2/3
    fields:
      description:
        label: Quick Description
        type: textarea
  - width: 2/3
    sections:
      recipeImages:
        type: image-clip
#        query: site.find('recipe').images
        layout: cards
#        template: image-clip
#        info: '{{ image-clip.dimensions }}'
#        image:
#          cover: true
#        min: 1
#        size: small
  - width: 1/3
    fields:
      cook:
        label: Recipe credit
        type: users
        multiple: true
      tags: true
  - width: 1/2
    fields:
      ingredients:
        label: Ingredients
        type: structure
        fields:
          ingredient:
            label: Ingredient
            type: text
  - width: 1/2
    fields:
      directions:
        label: Directions
        type: structure
        fields:
          step:
            label: Steps
            type: textarea
            size: large
