title: Recipe
type: recipe

icon: 🖼

status:
  draft: true
  listed: true

columns:
  - width: 1/1
    fields:
      headline:
        type: text
  - width: 1/3
    fields:
      cover:
        type: files
        layout: cards
        multiple: false
  - width: 2/3
    fields:
      description:
        type: textarea
  - width: 2/3
    sections:
      images:
        type: files
        layout: cards
        template: image
        info: "{{ file.dimensions }}"
        image:
          cover: true
        min: 1
        size: small
  - width: 1/3
    fields:
      tags: true
  - width: 1/2
    fields:
      ingredients:
        label: Ingredients
        type: textarea
        buttons:
          - ul
  - width: 1/2
    fields:
      directions:
        label: Directions
        type: textarea
        buttons:
          - ol
