title: Recipe

icon: 🥪

status:
  draft: true
  listed: true

columns:
  - width: 1/1
    fields:
      headline:
        type: text
  - width: 1/3
    fields:
      cover:
        type: files
        layout: cards
        template: cover
        multiple: false
  - width: 2/3
    fields:
      description:
        label: Quick Description
        type: textarea
  - width: 2/3
    sections:
      images:
        type: files
        layout: cards
        template: image
        info: "{{ file.dimensions }}"
        image:
          cover: true
        min: 1
        size: small
  - width: 1/3
    fields:
      cook:
        label: Recipe by
        type: users
        multiple: false
      tags: true
  - width: 1/2
    fields:
      ingredients:
        label: Ingredients
        type: structure
        fields:
          step:
            label: Steps
            type: text
  - width: 1/2
    fields:
      directions:
        label: Directions
        type: structure
        fields:
          step:
            label: Steps
            type: textarea
