title: Site

columns:
  - width: 1/2
    sections:
      recipes: sections/recipes
  - width: 1/2
    sections:
      drinks: sections/drinks
      pages:
        type: pages
        create: default
        template:
          - about
          - home
          - default
