title: Site

columns:
  - width: 1/1
    sections:
      recipes: sections/recipes
  - width: 2/3
    sections:
      drinks: sections/drinks
  - width: 1/3
    sections:
      pages:
        type: pages
        create: default
        template:
          - about
          - home
          - default
